### ISSUE TITLE
refactor(examples-basic): explain or don't destructure props in setup function

### ISSUE THREAD

**Issue by MacMaru** [Kong/swrv#102]
FTR: destructuring the props in the setup function is not advised since it removes reactivity, see https://v3.vuejs.org/guide/composition-api-setup.html#props

To mitigate future issues when users copy-paste this example, it might be good to either explain that reactivity isn't needed, or follow along with the composition-api-setup guide and not destructure props in setup arguments:

https://github.com/Kong/swrv/blob/cb7e99748e903323f46eaad42a7d37b0b9dcfad9/examples/basic/Repos.vue#L30

**Comment by darrenjennings** [comment]
Completely agree!
