### ISSUE TITLE
Module parse failed: Unexpected token (183:54)

### ISSUE THREAD

**Issue by sammustian** [Kong/swrv#103]
I've been trying to find a solution to my compilation issue. I am using the newest version of Vue CLI with Vue @2.6.11. I believe it's due to Vue CLI's method of using webpack but I can't figure out what the unexpected token is. Any thoughts?

```
Failed to compile.

./node_modules/swrv/esm/use-swrv.js 183:54
Module parse failed: Unexpected token (183:54)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         }
|         const fetcher = data || fn;
>         if (!fetcher || !isDocumentVisible() || (opts?.forceRevalidate !== undefined && !opts?.forceRevalidate)) {
|             stateRef.isValidating = false;
|             return;

**Comment by darrenjennings** [comment]
@sammustian ah looks like the bundle is a little too current. It assumes your bundler can handle optional chaining (it's at [stage 4](https://github.com/tc39/proposal-optional-chaining/) so it's pretty stable) but would recommend transpiling with the vue cli's babel plugin. Currently using https://github.com/Kong/swrv/blob/master/tsconfig.json#L4 `esnext`. I wonder if there is a better default or should bundle a es2015 (bigger output) for use cases like this.

**Comment by sammustian** [comment]
Thanks for the quick response. I'll look into adding optional chaining to my bundling and post back here when I get it working. This might not be an issue in future releases of Vue CLI or Vue 3 so at least we something here for people to reference.

**Comment by sammustian** [comment]
I've been unable to get '@babel/plugin-proposal-optional-chaining' to work with Vue CLI. I think the issue is within vue loader... definitely an odd bug.

**Comment by darrenjennings** [comment]
@sammustian targeting es5 now so should be ok in v0.8.1
