### ISSUE TITLE
How to "await" for fetch data from SWRV?

### ISSUE THREAD

**Issue by saturnonearth** [Kong/swrv#105]
I am trying to access the data object that is fetched from SWRV, but sometimes it is not there yet, so it is coming up undefined. Is there a way to get this data from SWRV using await/async? 

Thanks.

**Comment by darrenjennings** [comment]
@saturnonearth do you mean like async `setup` + suspense? You can do something like: https://github.com/darrenjennings/swrv-suspense

```ts
async setup(props) {
  const { data, mutate } = useSWRV<Pokemon>(
    () => `https://pokeapi.co/api/v2/pokemon/${props.pokeIndex}`,
    (key) =>
      fetch(key)
        .then((res) => res.json())
        .then((json) => ({ ...json, url: key }))
  );
  
  await mutate()

  return {
    data
  }
}
```

Otherwise, data being undefined is normal usage since it (most of the time) means the fetcher has not yet resolved. You can get the data also by watching it.

```ts
setup() {
  const { data, error } = useSWRV('/api/user', fetcher)
  
  watchEffect(() => {
    console.log(data.value) // do any logic here when data changes
  })

  return {
    data,
    error,
  }
},
```

**Comment by saturnonearth** [comment]
Is there a way to await for the data in the onMounted()? I am using data.value but it only works on refresh, not update. That is what I am struggling with. Because the data is not there yet from the fetcher from swrv

**Comment by darrenjennings** [comment]
@saturnonearth `async setup` is called before mount so the suspense method + `await mutate` should do as you are asking and will not render the component until the data is available. Otherwise you can v-if="data" the entire component but not sure what your goal is here.

**Comment by netiul** [comment]
In case you want to profit from the cache, conditionally `await mutate`.

```ts
async setup(props) {
  const { data, mutate } = useSWRV<Pokemon>(
    () => `https://pokeapi.co/api/v2/pokemon/${props.pokeIndex}`,
    (key) =>
      fetch(key)
        .then((res) => res.json())
        .then((json) => ({ ...json, url: key }))
  );
  
  if (!data.value) {
    await mutate()
  }

  return {
    data
  }
}
```
