### ISSUE TITLE
Fetching from disk-cache instead going out and grabbing file?

### ISSUE THREAD

**Issue by saturnonearth** [Kong/swrv#109]
I've noticed that when I go and fetch my JSON file, it seems to sometimes grab from the disk-cache instead, especially if I have dev console closed. Is this coming from SWRV or fetch?

![image](https://user-images.githubusercontent.com/12503538/100131373-f1ddb680-2e51-11eb-8ece-3fc867a7e4ad.png)

**Comment by darrenjennings** [comment]
@saturnonearth this is just normal browser cache. Browsers like chrome will read cache headers from server and store in memory or on disk. This is unrelated to swrv

**Comment by saturnonearth** [comment]
@darrenjennings Ok thanks, before I close, what would be the approach to prevent it from being cached?

**Comment by darrenjennings** [comment]
@saturnonearth typically you do something like `'Cache-Control': 'no-cache'` in headers of request.

**Comment by saturnonearth** [comment]
@darrenjennings Thanks!
