### ISSUE TITLE
Hello, Friends.

### ISSUE THREAD

**Issue by zhenzhenChange** [Kong/swrv#112]
Is there no ongoing maintenance for this library (Vue3 version)? It feels good, I like it!

**Comment by darrenjennings** [comment]
@zhenzhenChange the `beta` tag on npm is the vue 3 version. https://github.com/Kong/swrv/blame/master/README.md#L62-L68

Also see this comment for more context:
https://github.com/Kong/swrv/issues/107#issuecomment-728197369

**Comment by zhenzhenChange** [comment]
Yes, I understand.
I just had a look and the problem is similar to #113 .
I was also wondering yesterday why the value of `data` can be `undefined`.
When I use `data` in a `vue - template`, pressing F5 Refresh gives me the error: `data is undefined`.
I know this is a common asynchronous problem.
So used in `template`, usually with `v-if="data"` or `data && data.xxx`.

I'm wondering if  `useSWRV` to return a `Promise` instance, and then I `await` for it.  Would that be possible?

**Comment by darrenjennings** [comment]
> I'm wondering if useSWRV to return a Promise instance, and then I await for it. Would that be possible?

See responses here: https://github.com/Kong/swrv/issues/105
