### ISSUE TITLE
cache.ts API divergent from localStoreCache example in pwa and README

### ISSUE THREAD

**Issue by zoranpopovic** [Kong/swrv#119]
LocalStoreCache class in pwa example has very different interface than the memory version in cache.ts (different params, methods missing).  Also, the README has an even more out of date example of that class.  Ideally LocalStoreCache is an alternative option that is maintained and available in the library itself.

**Comment by darrenjennings** [comment]
@zoranpopovic i agree. We should add the cache strategies to the source and add tests
