### ISSUE TITLE
When first load is not on active tab, data is not fetched

### ISSUE THREAD

**Issue by santicros** [Kong/swrv#128]
When doing a load of a page while not in focus (we switch tab or have browser in background,...) requests are not made. I think we would like to have a first load of content and later revalidate on focus, but not have everything empty until the user focuses the page. Or if it's intended I believe it should be configurable. :)

Thanks so much!

**Comment by darrenjennings** [comment]
@santicros I don't follow, do you have a codesandbox with reproduction steps you can provide?

**Comment by santicros** [comment]
Hi @darrenjennings. Sure, I'll try to explain and show it better. Thanks for your time :)

## Problem

As SWRV only loads data when the page is on focus, if I have configured revalidateOnFocus to false there are some situations where data is **never** fetched:
If the page is first loaded on the background (for example, a user clicks on open in a new page on my page), the data will never be fetched if the page is user enters after Vue has loaded the page.

The only solution for now is setting revalidateOnFocus to true, so at first we don't have any data and then when the user focuses the page it fetches. But i see two problems here:
1. I think it would be useful, even if you have revalidateOnFocus to true, to have an option to fetch data at first load.
2. In my case I don't want to have revalidateOnFocus to true because I only want to have data fetched at load or when params change, not any time it focuses again.

## Solution

I think data should be fetched at first load OR we should add a new configuration like fetchDataOnFirstLoad or something to give an option to force a fetch on load.


## Reproduction

Here's a very simple demo: https://codesandbox.io/s/vue-swrv-demo-first-load-c3x98?file=/src/App.vue 

You have to open the demo in a new tab in the background and just wait a bit

And I've attached a video of the example :)


https://user-images.githubusercontent.com/24988424/105369066-7b1b2a80-5c02-11eb-939c-66c5be61b814.mov

**Comment by darrenjennings** [comment]
@santicros 💯 thanks for the great repro. It's clear now what's happening. I realize we need to do two things:

- `revalidate` should obey the `forceRevalidate` option when the document is not visible
- `mutate` should not care about visibility, so you should be able to call "mutate()" and force a revalidation

**Comment by santicros** [comment]
Thanks a lot for the fixes @darrenjennings!!
