### ISSUE TITLE
It's difficult serving from cache on key field if use 'Dependent Fetching' feature

### ISSUE THREAD

**Issue by lizy0329** [Kong/swrv#129]
Let us see demo:

```javascript
const {data: timeLineData} = useSWRV<Response>(
    () =>
        uid.value &&
        bid.value &&
        `/api/growth_report_time_line?version=10.6.0&uid=${uid.value}&bid=${bid.value}`,
    url => axios.get(url).then(r => r.data)
);

const {data: reportInfoData} = useSWRV<ReportInfoResponse>(
    () =>
        timeLineData.value.id &&
        `/api/get_growth_report_info?version=10.6.0&report_id=${
            timeLineData.value.id
        }&uid=${uid.value}&bid=${bid.value}`,
    url => axios.get(url).then(r => r.data)
);
```

**if i want to serve reportInfoData from cache**, what should I do?

**Comment by darrenjennings** [comment]
To [serve from cache only](https://github.com/Kong/swrv#serve-from-cache-only) you can set the fetcher to undefined. I haven't tested this code but I think something like this will work for you:

```ts
const defaultFetcher = (url) => axios.get(url).then(res => res.data)
const useRequest = (key, fetcher) => useSwrv(key, fetcher)
const { data: timeLineData } = useRequest(() => uid.value && bid.value &&
  `/api/growth_report_time_line?version=10.6.0&uid=${uid.value}&bid=${bid.value}`,
  defaultFetcher
)

const {data: reportInfoData} = useRequest(() => timeLineData.value?.id && 
  `/api/get_growth_report_info?version=10.6.0&report_id=${timeLineData.value.id}&uid=${uid.value}&bid=${bid.value}`,
  timeLineData.value?.id ? defaultFetcher : undefined
)
```

**Comment by lizy0329** [comment]
> To [serve from cache only](https://github.com/Kong/swrv#serve-from-cache-only) you can set the fetcher to undefined. I haven't tested this code but I think something like this will work for you:
> 
> ```ts
> const defaultFetcher = (url) => axios.get(url).then(res => res.data)
> const { data: timeLineData } = useSWRV(() => uid.value && bid.value &&
>   `/api/growth_report_time_line?version=10.6.0&uid=${uid.value}&bid=${bid.value}`,
>   defaultFetcher
> )
> 
> const {data: reportInfoData} = useSWRV(() => timeLineData.value?.id && 
>   `/api/get_growth_report_info?version=10.6.0&report_id=${timeLineData.value.id}&uid=${uid.value}&bid=${bid.value}`,
>   timeLineData.value?.id ? defaultFetcher : undefined
> )
> ```

I just want to say: 

A.component
```
reportInfoData is dependent on timeLineData to fetch data
```
B.component

 i want to serve reportInfoData from cache in B component
How to fill this key?
```
const {data: reportInfoData} = useSWRV(?, undefined)
```
