### ISSUE TITLE
How to destructure returned data?

### ISSUE THREAD

**Issue by bartenra** [Kong/swrv#130]
I am using a custom fetcher, but I am having trouble destructuring. This works:

```js
setup() {
  const { data } = useSWRV('/api/user', () => { ... }
  return { data }
}
```

This does not (omitting `setup()`):

```js
const { data: { virtualExpos } } = useSWRV('/api/user', () => { ... }
return { virtualExpos } 
```

This gives me "`toRefs() expects a reactive object but received a plain one`"

```js
const { data: { virtualExpos } } = useSWRV('/api/user', () => { ... }
const { virtualExpos } = toRefs(data)
return { virtualExpos }
```

Strangely enough, using this simple example:

```js
setup() {
  const { data } = useSWRV("https://cat-fact.herokuapp.com/facts")
  console.log("isReactive(data)", isReactive(data))
  return { data }
}
```

Prints `isReactive(data) false`...

Even though it is clearly reactive!

```js
const { data } = useSWRV("https://cat-fact.herokuapp.com/facts")
console.log("isReactive(data)", isReactive(data))
setTimeout(() => {
  data.value = "hello"
}, 5000)
return { data }
```

Works and will replace the result of the API call after 5 seconds.

Am I doing something wrong or is something weird going on?

Using Vue 2.6.12 and @vue/composition-api 1.0.0-rc.1...

**Comment by darrenjennings** [comment]
> Prints isReactive(data) false...

`data` is a [Ref](https://v3.vuejs.org/api/refs-api.html#ref)
https://github.com/Kong/swrv/blob/master/src/types.ts#L27

e.g. `console.log(isRef(data), isReactive(data)) // true, false`

**Comment by bartenra** [comment]
@darrenjennings Thanks for clarifying!

Any idea why destructuring is not working for me?

**Comment by darrenjennings** [comment]
@bartenra you _can_ destructure on useSwrv call directly (but I'm not sure this is what you want):

```ts
const { data: { value: myRefsValue } } = useSWRV('/api/user')
```

what are you trying to do exactly?

**Comment by oliverpool** [comment]
@bartenra maybe something like this?

```js

import { computed } from "@vue/composition-api";

return {
  virtualExpos: computed(() => data.value && data.value.virtualExpos),
}
```

**Comment by darrenjennings** [comment]
@bartenra yes @oliverpool's method is a good way to calculate a sub-object, for example with axios it can be onerous to constantly access `.data.data` so here's an example of how you might create a custom composable for such things:

```ts
export default function useRequest<Data = unknown, Error = { message: string }> (key: IKey, fn?: fetcherFn<AxiosResponse<Data>>, config?: IConfig) {
  const { data: response, error, isValidating, mutate: revalidate } = useSWRV<
    AxiosResponse<Data>,
    AxiosError<Error>
  >(key, fn, config)

  const data = computed<Data>(() => {
    return response.value?.data
  })

  return {
    data,
    response,
    error,
    isValidating,
    revalidate
  }
}
```
