### ISSUE TITLE
initialData option support

### ISSUE THREAD

**Issue by lixiaofeng666** [Kong/swrv#139]
like:
```js
const { data, error } = useSWRV(key, fetcher, {
  initialData: []
})
```

**Comment by darrenjennings** [comment]
see comment here: https://github.com/Kong/swrv/issues/18#issuecomment-600770690

> the composition api supports onServerPrefetch, which swrv takes advantage of and allows users to not have to change their client side code. We even added some specific nuxt code to take advantage of nuxt's hydration. If you are trying to prefill/warm the cache client side, you can call mutate directly.
