### ISSUE TITLE
Using Vuex with SWRV in Vue 3

### ISSUE THREAD

**Issue by bikingbadger** [Kong/swrv#145]
Hey there,
I'm trying to get swrv working with my vuex store. I understand that it could replace the store but I would like to get various sources using swrv and load them into the vuex store. Might not be the best practice and if so would love to learn how and why this is not the use case for swrv.

```
setup() {
    // Vuex store to add tasks and show tasks
    const store = useStore();
    const addTasks = (newTasks) => store.dispatch('addTasks', 'Todoist', newTasks);
    const tasks = computed({
      get: () => store.getters.allTasks,
      set: (listItem) => {
        store.dispatch('organiseTaskList', listItem);
      },
    });

    // Use SWRV to get todoist data
    const { data: todoistTasks, error: taskError } = useSWRV(Todoist.allTaskURL, fetcher);

    // Update the store using watch
    watch(todoistTasks, () => {
      console.log('Updated todist', todoistTasks);
      addTasks(todoistTasks);
    });

   // The idea is to add various sources and them combine them into a single store

   return {todoistTasks,taskError }
```

This is working
```
<template>
  <pre>TODOIST: {{ todoistTasks }}</pre>
</template>
```

So I can see that the data is being updated and if I output `todoistTasks` but is the watch how can I pass the values. The console.log shows the following:

```
Updated todist ObjectRefImpl {_object: Proxy, _key: "data", __v_isRef: true}
```

**Comment by darrenjennings** [comment]
@bikingbadger todoistTasks is a Vue `Ref`, so you have to access it via `todoistTasks.value` 
https://github.com/Kong/swrv/blob/bd6c7e6de2b8c2e9595b02fe1b010ac1a197cd37/src/types.ts#L27

**Comment by bikingbadger** [comment]
Works like a charm. Would it be worth creating a small example for this in the docs. I wouldn't mind putting something together. It's helping wrap my mind around how the internals work. Thanks for the help

**Comment by darrenjennings** [comment]
@bikingbadger sounds good, we can add a code snippet here: https://github.com/Kong/swrv/blob/master/docs/features.md#vuex

**Comment by bikingbadger** [comment]
I'll knock something together based on what I've done and then we can make improvements from there
