### ISSUE TITLE
useSWRV expects a "null" instead of an "undefined" for IKey

### ISSUE THREAD

**Issue by tmladek** [Kong/swrv#150]
If I use `swrv` with typescript, and I want to *not* fetch something, it's kind of awkward, because it's necessary to coerce the implicit `undefined` to `null` first, see this example from the README:

    const { data: projects } = useSWRV(() => user.value.id && '/api/projects?uid=' + user.value.id, fetch)

It fails to compile, because `Type 'undefined' is not assignable to type 'string | null'.`. One has to "convert" it like so:

    const { data: projects } = useSWRV(() => (user.value.id && '/api/projects?uid=' + user.value.id) || null, fetch)

I think it might be enough to just change the type of `IKey`, as I assume `useSWRV()` doesn't fail when passed `undefined` instead of `null`, if it's right there in the README.

Thanks!

**Comment by darrenjennings** [comment]
This would be a deviation from the swr types, and actually I only now realize we never run into this issue at Kong because we have yet to enable strict mode (i.e. `strictNullChecks`). curious @shuding do you know why the key should be `null` and never `undefined`?

**Comment by shuding** [comment]
@darrenjennings Oops it’s a mistake, it should allow any falsely values. Will get it fixed in the next version.
