### ISSUE TITLE
Initial data fetch not happening when `revalidateOnFocus: false` and document is not visible

### ISSUE THREAD

**Issue by tochoromero** [Kong/swrv#158]
When we have a swrv call with `validateOnFocus: false` and you open open a page on a new tab using the middle button (this makes it so the new tab is created but not focused) the initial data fetch doesn't happen, so when you finally focus on the tab there is no data loaded.

I was looking at the source code and I couldn't really find the problem but I think it is something around
https://github.com/Kong/swrv/blob/e7e5eaf931581119ca9f75ca4abdc2a43cfadf5f/src/use-swrv.ts#L241

If I remove `validateOnFocus: false` it works because as soon I focus the tab the data gets fetched. I understand why we may want to avoid fetching if the document is not visible, but I think we should have a global option to opt out.

On my opinion it should always fetch the very first time regardless of document visibility, but that is just my opinion.

Thank you for the good work!

**Comment by darrenjennings** [comment]
@tochoromero what version are you using? Can you repro with this sandbox? I am seeing the data loaded first time always: https://codesandbox.io/s/swrv-158-8lbs5

I also wrote this test which passes:

```ts
it('fetches data on first render even when document is not visible and revalidateOnFocus is false', async () => {
    toggleVisibility('hidden')

    const vm = new Vue({
      template: `<div>{{ data }}</div>`,
      setup  () {
        const { data, error } = useSWRV(
          'fetches-data-even-when-document-is-not-visible-1',
          () => new Promise(res => setTimeout(() => res('first'), 100)),
          {
            revalidateOnFocus: false
          }
        )
        return { data, error }
      }
    }).$mount()

    expect(vm.$el.textContent).toBe('')

    timeout(100)
    await tick()

    expect(vm.$el.textContent).toBe('first')
  })
```

**Comment by tochoromero** [comment]
You are right, my bad, I should had updated before creating the issue.
My problem was fixed with https://github.com/Kong/swrv/commit/ac9981615abadac080d4df3ea9ba325ef5ac54e4

Thank you very much.
