### ISSUE TITLE
Default fetcher breaks retrieving data from cache

### ISSUE THREAD

**Issue by tochoromero** [Kong/swrv#164]
A common use case we have in our applications is to have a top level component call `useSWRV` with a `fetcher`, but then have many lower level component call `useSWRV` with the same `key` but without providing a `fetcher` that way the children components can get the data without forcing to be fetched again, it is only the top level component that is concerned with revalidating the data.

This was working just fine before, but the introduction of a default fetcher changed that behavior, specifically this:
https://github.com/Kong/swrv/commit/a907d490b7a9db787427bfa28ed8c87eaa1cea47#diff-0988ac9996eafadcefcd62192f6fa8e63983c4d7b5d04c1604bb21d8096ef77cR185-R189

The documentation still talks about not passing a fetcher to force SWRV to use the cached values, but I don't think that is true anymore with the introduction of a default fetcher. I think having to opt in for the default fetcher is the way to go, maybe if you pass `true` as the second parameter it will use the default fetcher and if you pass `undefined` it will use no fetcher and it will fetch from the cache.

**Comment by darrenjennings** [comment]
@tochoromero re: https://github.com/Kong/swrv/issues/148#issuecomment-803730498 I have just [updated the docs](https://github.com/Kong/swrv/commit/8be65954a6f38f8b3063c6c4728c59f016dec022) so hopefully they are more obvious now to help out with this confusion. Thanks for flagging!

**Comment by tochoromero** [comment]
Thank you @darrenjennings. But I don't think the behavior is quite right. Specifically here:
https://github.com/Kong/swrv/blob/master/src/use-swrv.ts#L238

```js
const fetcher = data || fn
```

If `data` (the fetcher function) is `null`, as the documentation suggest, that expression will fallback to `fn` (the fetch api fetcher).

Instead, that line should probably be something like this:

``` js
const fetcher = data ?? (data === undefined ? fn : null)
```

**Comment by darrenjennings** [comment]
> data (the fetcher function) is null, as the documentation suggest, that expression will fallback to fn (the fetch api fetcher).

It's the reverse, docs say:
> If `null`, swrv will fetch from cache only and not revalidate. If omitted (i.e. `undefined`) then the [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) api will be used.

@tochoromero here is an example codesandbox, AFAICT it is working as expected https://codesandbox.io/s/swrv-157-79ek4 maybe there is something I am missing though.
