### ISSUE TITLE
revalidateOnMount

### ISSUE THREAD

**Issue by simowe** [Kong/swrv#196]
Is it possible to disable revalidation when the component mounts like the "revalidateOnMount" option in swr https://swr.vercel.app/docs/options?

Sometimes you might want to permanently cache data that is expensive to fetch, or you know it will never change.

If it does not exist, would you be interested in a pull request that adds this feature?

**Comment by darrenjennings** [comment]
@simowe it does not exist and yes I would be interested in a PR!

**Comment by adamdehaven** [comment]
This looks like the desired implementation; essentially forcing swrv to utilize the cache.
