### ISSUE TITLE
Minimal reproduction error: Cannot read property 'proxy' of null at useSWRV (use-swrv.ts:159)

### ISSUE THREAD

**Issue by mrweiner** [Kong/swrv#211]
This project doesn't seem to be working for me at all at the moment. At first I thought it was because I was using the [new <script setup> RFC](https://learnvue.co/2021/05/explaining-the-new-script-setup-type-in-vue-3-major-takeaways-from-the-rfc/), or trying to use it in `beforeMount()`, but I'm seeing the error (`Uncaught (in promise) TypeError: Cannot read property 'proxy' of null`) with a minimal reproduction as well. Any idea what might be going on?

```
<template>
  Hi!
</template>

<script>
import useSWRV from 'swrv';

export default {
  setup() {
    const { data, error } = useSWRV('https://jsonplaceholder.typicode.com/todos/1');

    return {
      data
    }
  }
}
</script>
```

**Comment by darrenjennings** [comment]
can you reproduce with a codesandbox or repo?

**Comment by mrweiner** [comment]
I think that this may have been some sort of environment issue because I can't seem to get it to happen again.
