### ISSUE TITLE
Retry on error after the component has been unmounted

### ISSUE THREAD

**Issue by tochoromero** [Kong/swrv#218]
When a SWRV calls fails by default it will keep trying to fetch data. This is great, the problem is the retries keep happening even after the component has been unmounted.

I believe it just need to check for `unmounted` [here](https://github.com/Kong/swrv/blob/e5694e175f545a6e3b7c08ec7f91da3116058029/src/use-swrv.ts#L273)

**Comment by darrenjennings** [comment]
@tochoromero sorry for the slow turnaround on responding to this, do you feel up to submitting a PR?

**Comment by adamdehaven** [comment]
This is resolved as of `1.0.1` 🚀
