### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'proxy' of null

### ISSUE THREAD

**Issue by xiaoxiaoqing-win** [Kong/swrv#219]
If use SWRV twice in a row, an error will be reported the second time,  for example:

const { data } =  useSWRV('XXX', XXX);   
const { data } = useSWRV('XXX', XXX);  // Uncaught (in promise) TypeError: Cannot read property 'proxy' of null

**Comment by darrenjennings** [comment]
@Alberqing can you provide a reproduction in code sandbox? Your code as is would throw a syntax error:
```
Uncaught SyntaxError: Identifier 'data' has already been declared
```
