### ISSUE TITLE
Destructured props in TypeScript setup loses reactivity

### ISSUE THREAD

**Issue by mythz** [Kong/swrv#228]
Because it took me a long time to figure out why it wasn't working, I wanted to raise my workaround for a reactivity issue with component properties as it's a gotcha that could save future devs time.

Basically useSWRV loses reactivity for properties in Vue TypeScript SFC's composition API setup script that uses destructuring assignment, e.g:

```html
<template>
{{ path }}
</template>
<script setup lang="ts">
import useSWRV from "swrv"
import { fetcher } from "@/api"

const { path } = defineProps<{ path:string }>() // doesn't support destructuring

const { data, error } = useSWRV(() => path, fetcher)
</script>
```

The Component Displays the updated `{{path}}` correctly but `useSWRV` is only fired once and can't detect any future changes to the components property.

The fix was to not use destructuring and reference the property through the props reactive object:

```html
<script setup lang="ts">
import useSWRV from "swrv"
import { fetcher } from "@/api"

const props = defineProps<{ path:string }>() // use props

const { data, error } = useSWRV(() => props.path, fetcher)
</script>
```

Not sure if this is a bug that can be fixed or something fundamental that prevents it from working, but IMO it's a natural gotcha for users to run into that took me a long time to workout. 

Feel free to close the issue if it's not something that can be fixed, the issue + workaround should still be searchable for anyone else running into this issue.

**Comment by souljorje** [comment]
@mythz hi! I think this is definitely not an issue. Use [toRefs](https://v3.vuejs.org/api/refs-api.html#torefs)  if you don't wanna loose reactivity.
```ts
const props = defineProps<{ path:string }>()
const { path } = toRefs(props)
const { data, error } = useSWRV(() => path, fetcher)
```

**Comment by mythz** [comment]
Thanks, it works when you dereference the string value, i.e:

```csharp
const props = defineProps<{ path:string }>()
const { path } = toRefs(props)

const { data, error } = useSWRV(() => path.value, fetcher)
```

Where it's replacing 1 reference to `props:Readonly<{ path:string }>` for a `path:Ref<string>` reference, but yeah I can see why a naked string value wouldn't be able to maintain reactivity, I just thought it was the reactive listeners was on the components props which triggered the rerender.  Since it's not, it looks like it's behaving as expected. 

Thanks for the feedback 👍
