### ISSUE TITLE
How to get the loading when re-fetching

### ISSUE THREAD

**Issue by daiyadove** [Kong/swrv#265]
I want to get the loading status even when I re-fetch.

With this method, I don't get the loading state when I re-fetch (validation, pagination, reactive parameter changes).
```
  if (data.value === undefined && !error.value) {
    state.value = STATES.PENDING
    return
  }
```
Is there any way to get the loading state even when re-fetching?

**Comment by darrenjennings** [comment]
Check out https://github.com/Kong/swrv#useswrvstate for a way to calculate states. You can use isValidating here.

**Comment by daiyadove** [comment]
thanks.
It's resolved!
By using isValidating, I was able to make the loading state due to parameter changes!
