### ISSUE TITLE
Switch to Vue 3 by default

### ISSUE THREAD

**Issue by ivos** [Kong/swrv#285]
Vue 3 has been around for almost 2 years now. The Vue official site has switched to Vue 3 by default some time ago.

It's time to merge branch `next` into `master` and support Vue 2 as a legacy option (depending on complexity).

**Comment by adamdehaven** [comment]
As a follow-up to this, I may suggest updating the `master` branch to Vue 2.7, which could then be the end-of-life for the Vue 2 supported version.

This could be published under a tag, and then make the Vue 3 version the default going forward under a breaking change (i.e. bumping the version to `1.x`)

**Comment by adamdehaven** [comment]
@ivos now that we've upgraded `swrv` to support Vue 2.7 (as of `0.10.0`) we plan to review and release the Vue 3 branch on the `master` branch in the coming month or so 👍🏼

**Comment by adamdehaven** [comment]
This will be resolved with https://github.com/Kong/swrv/pull/314

**Comment by adamdehaven** [comment]
The Vue 3 version `1.0.0` has been officially released on the `swrv@latest` tag on npm.
