### ISSUE TITLE
vue 3 support

### ISSUE THREAD

**Issue by darrenjennings** [Kong/swrv#29]
composition-api is a peerDep, but vue 3.x is in beta, so we should begin to test vue 3 as a peer dep as well

**Comment by muellercornelius** [comment]
That would be nice. Just ran in this issue some seconds ago ;(. Already someone working on it?

**Comment by darrenjennings** [comment]
@muellercornelius we're not using vue 3 at kong yet, but I got it working with https://github.com/vuejs/vite the other day (uses vue 3) just by removing the onServerPrefetch and ssr logic. Not sure on how best to release because I want to support both. I'll open up a `next` branch and see about getting the ci up and running.

**Comment by muellercornelius** [comment]
Yes I already tried somethings but not in depth. 

It is not very urgent for me ;).

**Comment by darrenjennings** [comment]
Fixed by https://github.com/Kong/swrv/releases/tag/v1.0.0-beta.1
