### ISSUE TITLE
Hey, is this library still maintained? Is there, maybe, a roadmap?

### ISSUE THREAD

**Issue by mv-go** [Kong/swrv#311]
My apologies for being so blunt with the title and many thanks for an amazing library!

I've been looking at commits here, especially at the `next` (vue3) branch. It doesn't seem, and please, by no means I intend to sound rude, that this library is actively maintained. I've had a look at #285 and #304, apparently major upgrade should be coming soon.

The only real reason I'm asking, I want to bring this library into a new large-scale project that my company is starting and I wouldn't want to rely on something that is going into not-maintained state.

Once again, my apologies if any of the above was disrespectful and big thanks for doing such a great work for an open-source community!

**Comment by adamdehaven** [comment]
No worries, happy to share some info.

If you reference the **Release strategy** section of #304:

> When we make the Vue 3 next branch the main branch in a future release, it will again bump the major version to 1.x

We upgraded for Vue 2.7 in #304. We plan to port those changes forward to the `next` branch, make necessary updates for Vue 3, and then merge `next` into `master` in the next ~month or so.

This means:

- The Vue 3 version (`1.x`) would become the default release version going forward. 
- The recently Vue 2.7 release (`0.10.0`) will be available via a npm tag of `@v2-latest`, following the core Vue lib's version tag strategy.
- The previous Vue < 2.7 release (`0.9.6`) will be available via a npm tag of `@legacy`
