### ISSUE TITLE
Could not get current instance, check to make sure that `useSwrv` is declared in the top level of the setup function.

### ISSUE THREAD

**Issue by abbjoafli** [Kong/swrv#318]
Hello im trying to use Swrv on my vue 2.6.14 app but i get the following error message "Could not get current instance, check to make sure that `useSwrv` is declared in the top level of the setup function.". I ues nuxt also.

I have the following in my package.json:
```
    "swrv": "^0.9.6",
 "@vue/composition-api": "^1.7.1",
    "nuxt": "^2.15.8",
```

And my code is the following:
```
<template>
  <div>
    <div>
      <div v-if="error">{{ error }}</div>
      <div v-if="data === undefined && !error">Loading...</div>
      <div v-if="data">
        <div>{{ data.body }}</div>
      </div>
    </div>
  </div>
</template>

<script>
import useSWRV from 'swrv'

const fetcher = (key) =>
  fetch(`http://localhost:3001/${key}`).then((res) => res.json())

export default {
  name: 'LoginPage',
  setup(props, context) {
    const { data, error } = useSWRV('ticket', fetcher)

    return {
      data,
      error,
    }
  },
}
</script>

```

**Comment by adamdehaven** [comment]
I don't really see anything here that would cause the error. I'd need a minimal reproduction via CodeSandbox or something in order to help debug.

**Comment by abbjoafli** [comment]
[Link to codesandbox](https://codesandbox.io/p/github/joflink/swrvtrouble/csb-ymkgz4/draft/dreamy-diffie?file=%2Fpages%2Flogin.vue&selection=%5B%7B%22endColumn%22%3A54%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A54%2C%22startLineNumber%22%3A3%7D%5D&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_SHELL_LOG%2522%252C%2522shellId%2522%253A%2522cl9yqjkuj000plri85kvi87vu%2522%252C%2522isMinimized%2522%253Afalse%252C%2522key%2522%253A%2522cl9yqjkuj000plri85kvi87vu%2522%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl9yqkxox009j2a6984dsfsb8%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Flogin%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl9yqkvm5007r2a69azm91g9i%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D). Thanks

**Comment by adamdehaven** [comment]
For starters, you don't have your `plugins/vue-composition-api.js` file registered as a plugin in the `nuxt.config.js` file; however, I still see the same error regardless.

If I had to guess, it's something to do with the versions that are being resolved in your project. If you look at [`swrv/examples/ssr-nuxt/` on this commit (`0.9.6` release)](https://github.com/Kong/swrv/tree/f64ceb5d97d037a4a51269c5c1e365631bb4f69b/examples/ssr-nuxt), everything is working as expected, so I'm guessing there's something going on with the specific dependency versions in your sandbox, or something else in the setup.
