### ISSUE TITLE
[Feature request] Allow use of useSWRV outside of setup()

### ISSUE THREAD

**Issue by matthew-dean** [Kong/swrv#343]
Right now, I'm trying to refactor a page that has cascading fetch calls. That is, based on the results of one call, it kicks of a different one using those as parameters.

To do that, it uses computed properties to set the value, which prompts a reactive response to kick of the second.

However, I discovered when using SWRV that this scenario is not supported at all, mostly because of [these lines](https://github.com/Kong/swrv/blob/master/src/use-swrv.ts#L162). 

I understand that the instance is not retrievable outside of setup, but could you add the ability to pass the instance somehow, or some other method so that fetch calls can occur anywhere? _Or_ alternatively, some way to set up the reactive object and defer fetching until later?

**Comment by matthew-dean** [comment]
Note also that the use of `getCurrentInstance()` is not supported by Vue.

> We exposed getCurrentInstance mostly for official libraries that need additional internal access, not for userland application code. It was mistakenly documented in WIP v3 docs but is no longer considered a public API.

**Comment by matthew-dean** [comment]
This solved my problem for me.

```diff
diff --git a/node_modules/swrv/dist/use-swrv.js b/node_modules/swrv/dist/use-swrv.js
index 3b38f2a..494b664 100644
--- a/node_modules/swrv/dist/use-swrv.js
+++ b/node_modules/swrv/dist/use-swrv.js
@@ -216,10 +216,10 @@ function useSWRV() {
     var isHydrated = false;
     var instance = (0, vue_1.getCurrentInstance)();
     var vm = (instance === null || instance === void 0 ? void 0 : instance.proxy) || instance; // https://github.com/vuejs/composition-api/pull/520
-    if (!vm) {
-        console.error('Could not get current instance, check to make sure that `useSwrv` is declared in the top level of the setup function.');
-        return null;
-    }
+    // if (!vm) {
+    //     console.error('Could not get current instance, check to make sure that `useSwrv` is declared in the top level of the setup function.');
+    //     return null;
+    // }
     var IS_SERVER = (vm === null || vm === void 0 ? void 0 : vm.$isServer) || false;
     // #region ssr
     /**
diff --git a/node_modules/swrv/esm/use-swrv.js b/node_modules/swrv/esm/use-swrv.js
index 2921590..ea0c312 100644
--- a/node_modules/swrv/esm/use-swrv.js
+++ b/node_modules/swrv/esm/use-swrv.js
@@ -211,10 +211,10 @@ function useSWRV() {
     var isHydrated = false;
     var instance = getCurrentInstance();
     var vm = (instance === null || instance === void 0 ? void 0 : instance.proxy) || instance; // https://github.com/vuejs/composition-api/pull/520
-    if (!vm) {
-        console.error('Could not get current instance, check to make sure that `useSwrv` is declared in the top level of the setup function.');
-        return null;
-    }
+    // if (!vm) {
+    //     console.error('Could not get current instance, check to make sure that `useSwrv` is declared in the top level of the setup function.');
+    //     return null;
+    // }
     var IS_SERVER = (vm === null || vm === void 0 ? void 0 : vm.$isServer) || false;
     // #region ssr
     /**
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by VoVAllen** [comment]
Or we should support usage like `app.use(SWRV)`, so that swr doesn't need to get vm when make requests

**Comment by adamdehaven** [comment]
I believe the suggestion by @memen45 [here](https://github.com/Kong/swrv/issues/343#issuecomment-1499290578) is what I would suggest as well.

Separately, the use of `getCurrentInstance` is essentially no longer necessary since SSR support was removed with [the release of version `0.10.0`](https://github.com/Kong/swrv/releases/tag/v0.10.0). I think the existing check is still technically fine as it causes `use-swrv` to exit if the instance cannot be found, meaning it is being called outside of the `setup` function. 

There are better ways to make this check, but since the method is still available, I lean on the side of doing nothing in order to prevent changes that are "under the hood" and do not impact anything functional.

**Comment by adamdehaven** [comment]
> Or we should support usage like `app.use(SWRV)`, so that swr doesn't need to get vm when make requests

I personally don't like this option; I'm not sure I see the value in registering the function globally on app init...?

**Comment by matthew-dean** [comment]
@memen45 

> As long as the inner function returns undefined, Swrv will not fetch anything.

Oh! That's good to know. I'd prefer to not patch the package if I don't have to. I'll try that, thanks. I'd still like to see this restriction to `setup()` removed though.

**Comment by matthew-dean** [comment]
@memen45 I'm looking at this a little more deeply. Can you tell me how changing the condition will cause a re-fetch? I thought only a reactive key could. Is the function a type of Vue reactive observer?

**Comment by adamdehaven** [comment]
See the section on "Dependent Fetching" here: https://docs-swrv.netlify.app/features.html#dependent-fetching

**Comment by vpitorri** [comment]
Hi @adamdehaven, I see you [replied](https://github.com/Kong/swrv/issues/343#issuecomment-1502197175) about the `setup()` limitation, would you mind expanding on that please?

We are evaluating the patch proposed [here](https://github.com/Kong/swrv/issues/343#issuecomment-1498408179) since with that we'd have a much cleaner/easier flow in our app by using it outside of `setup()`.

Functionality-wise everything seems to work correctly with that patch, even the localStorage usage, but it would be great to have a feedback from your side.

Thank you!

**Comment by VoVAllen** [comment]
> > Or we should support usage like `app.use(SWRV)`, so that swr doesn't need to get vm when make requests
> 
> I personally don't like this option; I'm not sure I see the value in registering the function globally on app init...?

That's not for registering the function globally, just for swrv to get the app context `app._context`

**Comment by adamdehaven** [comment]
@vpitorri the `setup()` function requirement must remain in place since `swrv` initiates calls in both the `onMounted` and `onUnmounted` hooks [here](https://github.com/Kong/swrv/blob/d94cd135c290ab98cda4675dd518a0024538b320/src/use-swrv.ts#L306-L423). 

These calls must be made from within the `setup()` function.

**Comment by vpitorri** [comment]
> @vpitorri the `setup()` function requirement must remain in place since `swrv` initiates calls in both the `onMounted` and `onUnmounted` hooks [here](https://github.com/Kong/swrv/blob/d94cd135c290ab98cda4675dd518a0024538b320/src/use-swrv.ts#L306-L423).
> 
> These calls must be made from within the `setup()` function.

@matthew-dean thank you for the reply and I'm sorry if this question might sound dumb, but what I'm not getting are the consequences of an usage outside of `setup()`.
I'm asking this only because it seems to be working correctly even if used outside of it (with the patch), so I'd love to understand what could be missing.

**Comment by matthew-dean** [comment]
@vpitorri ? Not sure you're asking the right person. Should be asked of the library author. In any case, I was able to figure out how to use dependent fetching to revert the patching method.

**Comment by dsolanorush** [comment]
@matthew-dean Might you be able to share a snippet of how you solved the use outside of setup using dependent fetching without the patch? I'm trying to `useSWRV` in a composable and running into the same issue.

**Comment by matthew-dean** [comment]
@dsolanorush It's just this: https://docs-swrv.netlify.app/features.html#dependent-fetching

If `useSWRV` is passed a function instead of a static key, and if that function references a reactive value, then it will re-compute when the reactive value changes. If the function returns a falsey value, it won't fetch. So, you can set up both in `setup`, but have the second `useSWRV` passed a function that depends on reactive value set by the first.

**Comment by adamdehaven** [comment]
Yep, exactly this ^^

Thanks for the detailed example

**Comment by dsolanorush** [comment]
@matthew-dean - Thanks for the clarification. I overlooked the `reactive value` part of dependency fetching. Much appreciated.

**Comment by anast3t** [comment]
Is it ok to define all useSWRV in app.vue and pass the result objects to e.g. state manager for use in other components/views? @adamdehaven 


The situation behind - i made a generic generating function to write lesser code with useSWRV, and wanted to make .ts request repositories. But only then found out that i can't use useSWRV outside setup. The workaround, that i thought about - is to call generating function with useSWRV for all requests in app.vue and pass the results to pinia stores as states.

generating func:
```typescript
function swrx<T>(
	requestType: RequestType,
	endpoint: string,
	args?: object,
	config?: IConfig
) {
	const requestFunc = reqType2reqFunc(requestType);

	if (args || requestType == RequestType.GET) {
		return useSWRV<T>(
			[endpoint, args],
			() => requestFunc(endpoint, args),
			config
		);
	} else throw new Error("Args are not the object");
}
```
usage:
```typescript
export const getSelf = () => {
	return swrx<User>(
		RequestType.GET, 
		'/self', 
		undefined, 
		{
			shouldRetryOnError: false,
			revalidateOnFocus: false
		});
};
```
App.vue
```typescript
import { useAuthStore } from "@/stores/auth";
import { getSelf } from "@/api/self";

useAuthStore().user = getSelf();
```

So if i "register" all other requests in App.vue, and not in separate components, will it be ok?
