### ISSUE TITLE
Exceed the quota exception

### ISSUE THREAD

**Issue by ThinhVu** [Kong/swrv#350]
Exceed the quota

<img width="769" alt="Screenshot 2023-07-02 at 6 36 45 AM" src="https://github.com/Kong/swrv/assets/8122962/ae3b5b3d-8c96-4901-ace4-7037b854abdc">

**Comment by adamdehaven** [comment]
The swrv cache, specifically localStorage, in all browsers has limits. It’s typically the responsibility of the host app to manage what it stores in the cache. 

We could add some error handling here around the `setItem` logic; however, this would likely suppress the error to the host application.

**Comment by ThinhVu** [comment]
> The swrv cache, specifically localStorage, in all browsers has limits. It’s typically the responsibility of the host app to manage what it stores in the cache.
> 
> We could add some error handling here around the `setItem` logic; however, this would likely suppress the error to the host application.

This is the PR. It does not aim to fix the bug, just ignore it to prevent application breaks:
https://github.com/Kong/swrv/pull/351

**Comment by adamdehaven** [comment]
This is now released in `1.0.4`
