### ISSUE TITLE
Cannot read property '$isServer' of null

### ISSUE THREAD

**Issue by bnason** [Kong/swrv#40]
Should `useSWRV` work in an on click handler? I'm getting the following error

```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property '$isServer' of null"

found in

---> <Home> at src/views/Home.vue
       <App> at src/App.vue
         <Root>
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property '$isServer' of null
    at useSWRV (use-swrv.js?7713:86)
    at onClick (Home.vue?76f2:16)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLButtonElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js?2b0e:6917)
```

Here is a minimal reproduction:
```
<template>
	<div>
		<button @click="onClick">Click me</button>
	</div>
</template>

<script>
import useSWRV from 'swrv';

const fetcher = async (key) => {
	return key;
};

export default {
	setup() {
		const onClick = () => {
			const { data } = useSWRV('test', fetcher);
			console.log(data)
		};

		return {
			onClick,
		};
	},
};
</script>
```

**Comment by darrenjennings** [comment]
`useSWRV` is a composition function, which is meant (by design of the vue composition api) to be invoked only in the `setup()` hook. So binding it in a click handler would result in errors. 

One option you can do is bind to a ref for the useSWRV cache key (e.g. `const hasClicked = ref(false)`) so that it only fires when you click.

```js
const hasClicked = ref(false)

const onClick = () => {
  hasClicked.value = true
};

const { data } = useSWRV(() => hasClicked.value && 'test', fetcher);

return {
  onClick,
};
```

**Comment by bnason** [comment]
Ah that makes sense. In my case, I was actually using it to verify inputs from the user. For example, they add a phone number to a list and I was kicking off swrv to get information about the number. The logic probably should have been in it's own component anyway so this will just force me to adhere to that philosophy :)
