### ISSUE TITLE
Get last known state of data if there is no `fn`

### ISSUE THREAD

**Issue by NeoLSN** [Kong/swrv#48]
In the case, we want to share data between components.

For example, there is an app config needs to be got from network when app is starting.
```
// in component App
const { data: appConfig } = useSWRV('/app/config', configFetcher);
....
// in component B
const { data: appConfig } = useSWRV('/app/config');
```

**Comment by darrenjennings** [comment]
`useSWRV` is purposefully aggressive on revalidation. So if you are trying to only fetch from cache then you can build your own composable.

```js
// useConfig.js
let config= null

function useConfig (fromCache = false) {
  if (fromCache && config) return { appConfig: config }
  const { data: appConfig } = useSWRV('/app/config', configFetcher);

  watch(appConfig, (newVal) => {
    config = newVal
  }, { immediate: true })

  return { appConfig }
}
```

```js
// in component App
const { appConfig } = useConfig();

// in component B
const { appConfig } = useConfig(true);
```

**Comment by NeoLSN** [comment]
The swr library won't do revalidate and will return the last known state of data when you call `useSWRV('/app/config')`.
https://github.com/vercel/swr/blob/master/src/use-swr.ts#L249

I'm just wondering that swrv can also do the same behavior if it is possible.

**Comment by darrenjennings** [comment]
@NeoLSN thanks for bringing this to my attention! Sounds like a good addition.
