### ISSUE TITLE
The behavior is unexpected when TTL value was set to 0

### ISSUE THREAD

**Issue by NeoLSN** [Kong/swrv#54]
https://github.com/Kong/swrv/blob/master/src/use-swrv.ts#L45

Sometimes we prefetch data when starting app.
```ts
mutate('/api/appConfig', fetcher);
```
and then use that data until use close window.
```ts
const { data } = useSWRV('/api/appConfig');
```
Because of the ttl, that data can be only kept 5 minutes.
That forced us need to do something like below.
```ts
mutate('/api/appConfig', fetcher, undefined, 1000 * 60 * 60 * 24 * 365);
const { data } = useSWRV('/api/appConfig', undefined, { ttl: 1000 * 60 * 60 * 24 * 365 });
```
I've looked the source codes. I know if the ttl is 0 means keeping the data and the refs forever.
So, could you please let the default ttl be 0?

**Comment by darrenjennings** [comment]
@NeoLSN when we use swrv, we actually wrap it in a custom hook so that the config is obfuscated from calls. In large apps with many swrv instances, much of the data does not need to live forever, but if you need to have some global config cached indefinitely, you can:

```ts
GLOBAL_CACHE_TTL = 0 // cached forever
function prefetch(url) {
  mutate('/api/appConfig', fetcher, undefined, GLOBAL_CACHE_TTL);
}

const useRequest(key, fetcher, config?) {
  return useSWRV(key, fetcher, {...config, ttl: GLOBAL_CACHE_TTL })
}
```

Does this work for your use case? Zero should work to cache forever, but you can also provide `Infinity` which is a javascript number instead of your 1 year cache if you prefer.

**Comment by NeoLSN** [comment]
@darrenjennings This way won't work, I've tried.

**Comment by darrenjennings** [comment]
@NeoLSN can you produce a failing test or example reproduction (e.g. codesandbox) so I can investigate?

**Comment by NeoLSN** [comment]
Here you are.
https://codesandbox.io/s/eager-blackburn-7ni0j?file=/src/components/HelloWorld.vue

Click button and observe the data change.
After 5 minutes, you can try click buttons or switch page.

**Comment by NeoLSN** [comment]
https://github.com/Kong/swrv/blob/master/src/use-swrv.ts#L60-L62

I think this is the issue.

**Comment by darrenjennings** [comment]
@NeoLSN thanks for looking into it! Let me know if you are able to issue a PR with tests, otherwise I'll take a look when I can.

**Comment by NeoLSN** [comment]
https://github.com/Kong/swrv/pull/56
