### ISSUE TITLE
Allow array as key, multiple arguments to fetcher

### ISSUE THREAD

**Issue by hdahlheim** [Kong/swrv#55]
In the [parameter documentation](https://github.com/Kong/swrv#parameters), the readme mentions that it is possible to pass an array as a cache key to useSWRV, presumably to allow passing multiple arguments to the fetch function as SWR does.

Currently, this does not work and it brakes the caching completely. 

Is there a plan to support this feature, or is there another way to pass multiple arguments to the fetcher function?

**Comment by darrenjennings** [comment]
@hdahlheim yes this is a documentation error. Here's the type in case you need to see what it accepts at the code level:

https://github.com/Kong/swrv/blob/22eea04e7a927c3f1c08d82e2364c3b7c4e97424/src/types.ts#L25

Currently we only support [watcher signatures](https://github.com/Kong/swrv/blob/22eea04e7a927c3f1c08d82e2364c3b7c4e97424/src/use-swrv.ts#L310) to build the
the cascade/dependencies, and you must return a string. e.g.

```ts
const endpoint = ref('/api/user')
const userId = computed(() => $route.params.id)
const { data, error } = useSWR(() => `${endpoint.value}/${userId.value}`, fetcher);
```

Keeping this ticket open so that we can have parity with `swr` which supports serialization of key arrays https://github.com/vercel/swr/blob/1882cbd410f1dbf8017997af5f3383ad07090346/src/cache.ts#L59. The nice thing about swrv is that the keyFunction takes advantage of vue watchers and tracks all dependencies, so you don't _have_ to send back an array, just a function that accesses observable objects (refs/computed) and swrv will revalidate based on what dependencies have changed in the key. I could see this being nice to pass multiple arguments to the fetcher function though which is not yet supported.

**Comment by hdahlheim** [comment]
Hey @darrenjennings, after looking at the [Composition API RFC](https://composition-api.vuejs.org/api.html#watch) again, I noticed that an array is also a valid source for the `watch` function. I don't know if this helps in any way. The serialization of the cache key might be a more complicated problem.

The ability to pass multiple parameters to the fetcher function would help me a lot in our current Vue 3 project. 

If there is something I could do to help, let me know. I don't have much experience with typescript or contributing to libraries, but I'm happy to help.

**Comment by maoberlehner** [comment]
Really quick and **_dirty_** workaround for the time being:

```js
// Object as key
useSwr(() => JSON.stringify({ path: path.value }), paramString => pageService.load(JSON.parse(paramString)));
// Multiple parameters as array
useSwr(() => JSON.stringify([path.value, id.value]), paramString => pageService.load(...JSON.parse(paramString)));
```

**Comment by darrenjennings** [comment]
@maoberlehner as far as I can tell your suggestion would still require a serialization so that cache data can be stored/retrieved? Seems to hold true regardless of variadic/array arguments.

btw, love the blog and glad to run into you on github!

**Comment by maoberlehner** [comment]
> btw, love the blog and glad to run into you on github!

Thanks, nice too meet you ;)
I was glad to find this project when I was searching for a SWR solution for Vue!

> @maoberlehner as far as I can tell your suggestion would still require a serialization so that cache data can be stored/retrieved? Seems to hold true regardless of variadic/array arguments.

Yes, serialization and hashing is still necessary. Just wanted to take the chance to propose a function signature that I like better than the one `swr` is using 😅

**Comment by maoberlehner** [comment]
After taking a closer look at react-query and swr I think react-query does this best: https://react-query.tanstack.com/docs/guides/queries#query-keys

In swr two objects with the same property values would be treated as different cache keys. In react-query on the other hand, `const object1 = { a: ‘a’ }` and `const object2 = { a: ‘a’ }` would both hit the same cache.

And it is probably best to stick to the same function signature too. So users who already know the other tools have an easier time.

**Comment by maoberlehner** [comment]
I like the serializer as a config a lot! The `swr` serializer is very limited and only works with strings as far as I can see. Which limits the possibilities tremendously and leads to unexpected behavior (two objects with same properties return different cashes).

On the other hand, I just realized that the way how I want to use this package leads to a different problem: **two objects with the same properties but a different `fetcher` function return the same cache.**
So basically for this uses case, no matter if using the `swr` or `react-query` serializer strategy, one has to use a wrapper function to create a unique cache key also taking the `fetcher` function into account.

```js
function stringifyCacheKey({ id, key }) {
  // For best results, if `options` is an object, its
  // properties should be ordered alphabetically also.
  return JSON.stringify({ id, key });
}

function parseCacheKeyString(string) {
  return JSON.parse(string);
}

function wrappedUseSwr(id, key, fetcher, ...otherParams) {
  return useSwr(
    stringifyCacheKey({ id, key }),
    cacheKeyString => fetcher(parseCacheKeyString(cacheKeyString).key),
    ...otherParams,
  );
}

const CACHE_ID = 'USER_SERVICE';

function useUserService(params) {
  // Without a unique CACHE_ID for each `fetcher` function,
  // if you load User 1 with params `{ id: 1 }` or in another
  // `useArticleService` you load Article 1 also with `{ id: 1 }`
  // you would hit the same cache.
  return wrappedUseSwr(CACHE_ID, params, userService.load);
}
```

If I understand the react-query serializer config implementation correctly, this could be done with a custom serializer I think.

> Would you be open to contributing?

I decided to pause my open source work and only do what's absolutely necessary in my own projects.
