### ISSUE TITLE
swrv can not deal with onClick event?

### ISSUE THREAD

**Issue by lizy0329** [Kong/swrv#75]
I want to use like this:
```javascript
// request.js
const useGetCard = (key) => {
  const {data, mutate} = useSWRV(key, fetcher)
  return {state: data, mutate}
}
```

```javascript
// Vue
<div @click="getCard">Click me!</div>

const {state, mutate} = useGetCard('getCard')

const getCard = async () => {
  const result =  await mutate()

  console.log(result .msg)
}

return {
  getCard
}
```
It's all right use mutate function like this?
and how to disabled fetch data when enter the page?

**Comment by darrenjennings** [comment]
@lizy0329 yes that is totally acceptable usage of mutate. Are you running into any issue? Also, you can disable window focus through config `revalidateOnFocus: false`
