### ISSUE TITLE
mutate error: TypeError: fetcher is not a function

### ISSUE THREAD

**Issue by lizy0329** [Kong/swrv#85]
Vue version: @vue/composition-api

mutate error: TypeError: fetcher is not a function

If I return mutate method directly.

```
<div @click="mutate "></div>

// js
const { data, mutate } = useSWRV(
      "https://xxx.com/Wap/Activity/agreement",
      fetcher
);

return {
    mutate
}
```

But if I use reSend function call mutate, It done!

```
<div @click="reSend"></div>

// js
const { data, mutate } = useSWRV(
      "https://xxx.com/Wap/Activity/agreement",
      fetcher
);

const reSend = () => {
    mutate();
}

return {
    reSend 
}
```

**Comment by darrenjennings** [comment]
I'm a little confused, you do not have a fetcher function and your mutate doesn't have any data?

**Comment by lizy0329** [comment]
> I'm a little confused, you do not have a fetcher function and your mutate doesn't have any data?

It’s just missing here，I’ll fix it

**Comment by darrenjennings** [comment]
@lizy0329 I can not see how you are defining fetcher, so it is not clear if the error is real or not. Can you reproduce via codesandbox please? I tried here: https://codesandbox.io/s/swrv-minimal-hcp42

**Comment by lizy0329** [comment]
> @lizy0329 I can not see how you are defining fetcher, so it is not clear if the error is real or not. Can you reproduce via codesandbox please? I tried here: https://codesandbox.io/s/swrv-minimal-hcp42

yes, try [this one](https://codesandbox.io/s/bold-satoshi-f9x5s?file=/src/App.vue)

**Comment by darrenjennings** [comment]
@lizy0329 this is because your codesandbox is actually passing the event of the button click to `mutate` as the first argument. Changing to `<button @click="() => mutate()">revalidate</button>` fixes it.

**Comment by lizy0329** [comment]
Thanks a lot!
