### ISSUE TITLE
IResponse - mutate no argument?

### ISSUE THREAD

**Issue by lizy0329** [Kong/swrv#87]
In types.d.ts file, I can see
```
export interface IResponse<Data = any, Error = any> {
    data?: Ref<Data | undefined>;
    error?: Ref<Error | undefined>;
    isValidating: Ref<boolean>;
    mutate: () => Promise<void>;
}
```
mutate: () => Promise<void> has no argument

But when I see source code

```
return {
    ...toRefs(stateRef),
    mutate: revalidate
  } as IResponse<Data, Error>

// Revalidate the cache, mutate data
const revalidate = async (data?: fetcherFn<Data>) => {...}
```

Just like https://swr.vercel.app/docs/mutation#bound-mutate

**Comment by darrenjennings** [comment]
looks like an oversight, the mutate function returned from useSwrv should be like the global mutate but without having to set the cache key and able to receive a parameter to set data. I think initially it was just a "revalidate only" but now it should have the argument (and hopefully it should work with just a change to they types).

**Comment by lizy0329** [comment]
Now, even if I use mutate ({ Foo: ‘Bar’}) in js, console will emit the error “ fetcher is undefined”.
From debugger, promiseFromCache get nothing leads to enter the first logic block

```js
const promiseFromCache = PROMISES_CACHE.get(keyVal);

if (!promiseFromCache) {
    const newPromise = fetcher(keyVal);
    PROMISES_CACHE.set(keyVal, newPromise, config.dedupingInterval);
    await mutate(keyVal, newPromise, config.cache, ttl);
}
else {
    await mutate(keyVal, promiseFromCache.data, config.cache, ttl);
}
```

**Comment by lizy0329** [comment]
> looks like an oversight, the mutate function returned from useSwrv should be like the global mutate but without having to set the cache key and able to receive a parameter to set data. I think initially it was just a "revalidate only" but now it should have the argument (and hopefully it should work with just a change to they types).

Bound-mutate is very suitable for stage that require quick response, such as post comments, and then require consistency

**Comment by darrenjennings** [comment]
@lizy0329 do you feel up to submitting a PR with a fix?
