### ISSUE TITLE
Mutate doesn't recheck dependent key

### ISSUE THREAD

**Issue by santicros** [Kong/swrv#90]
Hi again,

I've found that when doing mutate() of a useSWRV query, the key is not validated again.

Example:

useUser.js
```js
export default function useUser() {
  const checkIsValid = () => {
    console.log('ACCESSSED CHECK IS VALID');
    return false;
  };
  return useSWRV(() => checkIsValid() && 'user', fetchUser);
}
```

In a component:
```vue

<template>
  <button @click="checkAgain">CHECK</button>
</template>
<script>
import useUser from '../hooks/useUser.js';

export default {
  setup(){
    const { mutate, data } = useUser();

    const checkAgain = () => {mutate()};

    return {checkAgain}
   }
}
</script>
```

The function checkIsValid is only executed once (when the component loads). When I do mutate() the checkIsValid is not executed, as so, its always false. If the first time is true, every time is executed. So it's not validating it again.

In my case I wanted to check the token stored at the localstorage, but found out that it's not checking it.

Thanks.

**Comment by darrenjennings** [comment]
swrv keys are watchers, so if you want to fire the cache key function again to check, it will need to include a reactive object. something like:

```ts
function useUser(user: Ref<User>) {
  const isValid = computed(() => !!user.value)

  return useSWRV<User>(() => isValid.value && 'user', fetchUser);
}
```

**Comment by santicros** [comment]
Thanks for the fast response, I see!
Yet not sure how would I do it if what I want to do is check the localstorage...

Have tried this but is not working 😅: 

```js
export default function useUser() {
  const isValid = ref(window.localStorage.getItem('token'));

  return useSWRV(() => isValid.value && 'user', fetchUser);
}
```

Thanks so much!

**Comment by darrenjennings** [comment]
wherever you are mutating localStorage will also need to update the ref. So you would want to use some reactivity in a global store to mutate the user's tokens. This is where something like vuex or https://github.com/posva/pinia can help e.g. 

```js
// example store.js
const token = ref(window.localStorage.getItem('token'))

export default {
  token,
  getToken() { return token.value }
  setToken(token) { window.localStorage.setItem('token', token); token.value = token }
}
```

```js
import store from './store.js'
export default function useUser() {
  return useSWRV(() => store.token && 'user', fetchUser);
}
```

**Comment by santicros** [comment]
Thanks for your explanation and the example. I have it clear now, will try that. Thanks!!
