### ISSUE TITLE
Not working in Nuxt v2.14.5 ?

### ISSUE THREAD

**Issue by saturnonearth** [Kong/swrv#98]
I have spent a while trying to get this to work with the latest version of Nuxt, but it does not seem possible. I keep getting 
`You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file` for Fetcher. The examples for SSR in this repo are using 2.11. Is there something in more recent versions that break this?

Edit: This may be an issue on my end I am not sure. I am getting odd results. Can you confirm with works with latest version of Nuxt?

Edit 2: It seems like it may have been from using the latest version of @vue/composition-api.

**Comment by darrenjennings** [comment]
@saturnonearth I have updated the axios-typescript-nuxt example in the `examples` dir of this repo. The app starts up (`yarn dev`) and works as expected. Can you provide a repo or codesandbox that reproduces your error?

**Comment by saturnonearth** [comment]
Hi there,

It appears it was something to do with with the most recent version of the vue composition API, I believe it was requiring Vue 3.
